<?php
require_once('/PHPMailer-master/PHPMailerAutoload.php');

function ac_mail( $address, $body){

	$mail             = new PHPMailer();
//	$body             = file_get_contents('contents.html');
//	$body             = eregi_replace("[\]",'',$body);

	$mail->IsSMTP(); // telling the class to use SMTP
	$mail->SMTPDebug  = 0;                     // enables SMTP debug information (for testing)
											   // 1 = errors and messages
											   // 2 = messages only
	$mail->SMTPAuth   = true;                  // enable SMTP authentication
	$mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
	$mail->Host = 'smtp.gmail.com';
	$mail->Port       = 587;                    // set the SMTP port for the GMAIL server
	$mail->Username   = "alebaggio91@gmail.com"; // SMTP account username
	$mail->Password   = "diegoanna";        // SMTP account password

	$mail->SetFrom('alebaggio91@gmail.com');

	$mail->AddReplyTo("alebaggio91@gmail.com");

	$mail->Subject    = "Password";

	$mail->AltBody    = "To view the message, please use an HTML compatible email viewer!"; // optional, comment out and test
	echo "1";
	$mail->MsgHTML($body);
	echo "2";
	$mail->AddAddress($address);
	echo "3";
	if(!$mail->Send()) {
	  echo "Mailer Error: " . $mail->ErrorInfo;
	  return false;
	} else {
	  echo "Message sent!";
	  return true;
	}
}

function ac_mail_no-reply($email_to, $email_object, $email_content){
	$email_message = "<html><body><h1>".$email_object."</h1><p>This is an autogenerated message, please do not reply at this address.</p><br /><br />".$email_content."<br />";


	function clean_string($string) {
		$bad = array("content-type","bcc:","to:","cc:","href");
		return str_replace($bad,"",$string);
	}

	$email_message .= "</body></html>";

	$emailSegreteria = 'no-reply@checkcables.com';


	$from = $emailSegreteria;
	$to = $email_to;
	$subject = $email_object;
	$message = $email_message;
	// a random hash will be necessary to send mixed content
	$separator = md5(time());
	// carriage return type (we use a PHP end of line constant)
	$eol = PHP_EOL;
	// attachment name
	// encode data (puts attachment in proper format)

	// main header (multipart mandatory)
	$headers = "From: ".$from.$eol;
	$headers .= "MIME-Version: 1.0".$eol;
	$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"".$eol.$eol;
	$headers .= "Content-Transfer-Encoding: 7bit".$eol;
	$headers .= "This is a MIME encoded message.".$eol.$eol;
	// message
	$headers .= "--".$separator.$eol;
	$headers .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
	$headers .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
	$headers .= $message.$eol.$eol;
	// send message
	return mail($to, $subject, "", $headers);
}
?>
    